### ISSUE TITLE
switch views through segmented control

### ISSUE THREAD

**Issue by jannydiu** [uchicago-mobi/MPCS51030-2019-Winter-Forum#107]
Can you provide any tips about how to switch views through segmented control? Do we need to add container view?

**Comment by susanstevens** [comment]
You don’t necessarily need to display a different view when the user taps on the segmented control. You just need to display a different number of cells.

You might find it helpful to create two arrays to represent the data being displayed. And remember that you can tell your collection view to reload data whenever you need to re-trigger your data source methods.
