### ISSUE TITLE
Heart Icon to show favorited Albums

### ISSUE THREAD

**Issue by eealexander2** [uchicago-mobi/MPCS51030-2019-Winter-Forum#108]
Hello! Is it ok if I just display a small image of a heart at the very bottom right of the album if the user has favorited it? Or does the heart need to be a different type of object? Thanks!

**Comment by ab1470** [comment]
I was wondering the same thing. I think #105 answers it!

**Comment by susanstevens** [comment]
Yep, using an image view works fine!

**Comment by eealexander2** [comment]
Thanks!
