### ISSUE TITLE
Implementing MVVM pattern

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#109]
I understand the idea behind MVVM, but I've really struggled with implementing it. 

In my project, I have an Album struct (the model), an AlbumViewModel struct (the view model), and an AlbumService class that handles the networking. My understanding of MVVM is that the View Controllers should never interact with an Album object, instead only interacting with AlbumViewModel objects. 

I'm confused about where in my code I should store the results of my API request into Album objects, and when I convert those album objects into AlbumViewModel objects. Should make an API call, store the results of that API call as an array of Album objects, then loop through each of those album objects to convert them into AlbumViewModel objects? If that's correct, would it be reasonable to handle all of that in a function of the AlbumService class?

**Comment by hbennett766** [comment]
MVVM = Model View View Model

Model: `Album`
View: `<your view controller>`
View Model: `AlbumViewModel`

The `Album` object and the `AlbumViewModel` object are two separate things in MVVM. You wouldn't convert one to the other. The `Album` object is going to look just like all the other structs that you've built using JSON in past weeks. We're just adding a "middle man" between that model object and the view controller. Enter `AlbumViewModel`.

`AlbumViewModel` will store things that don't come back from the JSON, but would be useful when prepping the model object for use by the view controller. In this particular case, a perfect `var` to include in your `AlbumViewModel` would be `var isFavorite: Bool`.

So when you fetch your data, yes, you would loop through each model object, and create one view model for each. Furthermore, If you initialize your view model with the album you're at in the loop, you would never have to touch your model object again, and the view model can be the object with which the view controller communicates. The "middle man".
```
for album in albums {
    albumViewModels.append(AlbumViewModel(album: album))
}
```
```
// pseudocode for some things the view model might contain
Album View Model {
    album
    isFavorite
    formattedReleaseDate
    lyricsExcerpt
}
```
Lmk if you have any questions!

**Comment by ab1470** [comment]
I think I got it now. Thanks!
