### ISSUE TITLE
UIButton image size is very different in interface builder vs simulator

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#111]
<img width="344" alt="screen shot 2019-02-25 at 9 17 09 pm" src="https://user-images.githubusercontent.com/22333279/53385331-aaa45800-3943-11e9-9761-25b7622a88e2.PNG">

<img width="344" alt="screen shot 2019-02-25 at 9 17 09 pm" src="https://user-images.githubusercontent.com/22333279/53385377-d0c9f800-3943-11e9-9729-c85bbf802b37.png">

In order for my UIButton's heart icon to be a reasonable size when I run my app in Simulator (first photo), I have to make the icon huge in Interface Builder (second photo). Any idea why this happens? I've played around with the UIButton's content mode settings (below) to no avail. 

<img width="460" alt="screen shot 2019-02-25 at 9 28 13 pm" src="https://user-images.githubusercontent.com/22333279/53385523-43d36e80-3944-11e9-9db1-abdb50e7b8a4.png">

**Comment by hbennett766** [comment]
Does the heart have any layout constraints? If not, try setting some, and see if that helps.

Is your image asset set to 1x/2x/3x individual scales? If so, are the images _actually_ 1x/2x/3x (e.g. 20x20, 40x40, and 60x60)? Check out this link for [adjusting to a single scale](https://useyourloaf.com/blog/xcode-9-vector-images/)
