### ISSUE TITLE
Warning: UIImageView.image must be used from main thread only

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51030-2019-Winter-Forum#112]
In order to satisfy the instructions "Do not download images on the main queue", I am using the global queue: 
`DispatchQueue.global(qos: .userInitiated).async { completion(image, nil) }`
to download the image and update a `CollectionViewCell.UIImageView.image`, which results in the title warning. I've since read that you are not supposed to interact with any UIKit elements from outside the main thread. What is the best way to accomplish this?

**Comment by hbennett766** [comment]
There are two distinct actions happening here.

1. Fetch the image
2. Add the image to the collection view

Task 1 should happen on the background thread, which you have properly set up.

Task 2 should happen on the main thread. You are correct, we should always perform UI work on the main thread. UI work on a background thread causes UI lag and delays, which results in a bad user experience.

Inside your image fetch completion, explicitly grab the main thread to perform your UI work, just as you have done in both past assignments and with the iTunes album fetch in this assignment.

Does this make more sense?

**Comment by lmnoel** [comment]
Yeah, that makes complete sense and fixed the warning.
