### ISSUE TITLE
How to dismiss the DetailViewController?

### ISSUE THREAD

**Issue by lizefei** [uchicago-mobi/MPCS51030-2019-Winter-Forum#115]
If I simple ctrl drag the tap gesture recognizer back to the collection view controller, it will clear all the data(i.e. the downloaded album array) in the collection view controller.

**Comment by susanstevens** [comment]
You might want to try adding the tap gesture recognizer to the detail view controller and adding an IBAction there. There is a method on `UIViewController` that a modally-presented view controller can call to dismiss itself: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismiss.
