### ISSUE TITLE
Problems with reuse identifier

### ISSUE THREAD

**Issue by jbreynier** [uchicago-mobi/MPCS51030-2019-Winter-Forum#116]
I keep getting this error message when I try to run the app: "collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath" 

However, I did set the identifier for the cell, and I use it in the cellForItemAt function, so I don't know where the issue is.

**Comment by hbennett766** [comment]
Inside cellForItemAtIndexPath, what is the line of code you’re using to assign the cell,
```
let cell = // something
```

**Comment by jbreynier** [comment]
guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "albumCell", for: indexPath) as? AlbumViewCell else { return UICollectionViewCell() }

**Comment by hbennett766** [comment]
And your reuse identifier is set to “albumCell”? Can you double check that? If it is, can you push your code to your repo? I’ll take a look

**Comment by jbreynier** [comment]
Yes it is. I already pushed my code to my repository. Thank you!

**Comment by hbennett766** [comment]
In `viewDidLoad`, you register the cell for reuse with this line:
```
self.collectionView!.register(UICollectionViewCell.self, forCellWithReuseIdentifier: reuseIdentifier)
```

2 issues with this line, one is causing the crash. The other is that you don't need the force unwrap after collection view. So removing that, we get:
```
self.collectionView.register(UICollectionViewCell.self, forCellWithReuseIdentifier: reuseIdentifier)
```

Do you know what the crash bug is?

**Comment by jbreynier** [comment]
I changed UICollectionViewCell to AlbumViewCell, and that seems to have solved part of the problem. However, now I get the following error message when I try to assign properties to the images on the AlbumView Cell: Unexpectedly found nil while unwrapping an Optional value

**Comment by hbennett766** [comment]
This means that something with a `nil` value is being force-unwrapped. Do you know what that object is?

If not, the `po` debugging statement is helpful. Make your app crash again, and look at the line that is red. `cell.heartImage.alpha = 0`. There are two objects being accessed here, the `cell` object, and the `heartImage` object.

In your debugger window (see below for a screenshot), type `po cell` and hit return. Then type `po heartImage` and hit return. Which object is `nil`?

<img width="536" alt="screen shot 2019-02-27 at 8 47 42 am" src="https://user-images.githubusercontent.com/10427644/53498825-bccde580-3a6c-11e9-97df-bd4e60f07c31.png">

**Comment by hbennett766** [comment]
Hey while you're working in here, your image fetch is currently happening on the main thread, which we don't want. All networking should happen on a background thread, so as not do interrupt the user interface tasks. Place that call to `getImage` explicitly on a background thread, then do the UI work in the completion block explicitly on the main thread. Does this make sense?

**Comment by jbreynier** [comment]
I added a function to deal with downloading an image outside the cellForItemAt function, and then called it in the cellForItemAt function. 

I checked and saw that heartImage and albumImage are both null. However I still do not understand why that is, since I have an IBOutlet in my AlbumViewCell class for both images, and this worked in my last project (the What's In The News). Do I need to somehow initialize both heartImage and albumImage?

**Comment by susanstevens** [comment]
I would recommend deleting this line:

```swift
self.collectionView!.register(UICollectionViewCell.self, forCellWithReuseIdentifier: reuseIdentifier)
```

That line is included when you create a collection view controller using "Cocoa Touch Class" instead of "Swift File", and it essentially overrides the work you've done to set up the cell in storyboard. 

It's a good idea to review the code created automatically by Xcode and delete anything you don't actually need. (It would also be nice if Apple didn't mysteriously add this line for you, but... sigh.)
