### ISSUE TITLE
Two questions.

### ISSUE THREAD

**Issue by michaelsoren** [uchicago-mobi/MPCS51030-2019-Winter-Forum#12]
I am doing the app icons and I am currently getting this warning message related to the app icons.

![image](https://user-images.githubusercontent.com/25490468/51152910-8f6a0700-1833-11e9-98a4-5851e0c0efd0.png)

Do I need to comply with these as well? Since you did not ask for me to add app icon images of those sizes, not really sure if I should handle it.

The answer is probably “yes”, but might as well ask.

Other question I had was that I accidentally did the 4th sectopm of the tutorial. I thought we were supposed to do it, so my implementation has the stars fully functional. Is this alright? I really don’t want to try and roll it back to just the first three parts, it seems like a waste.

**Comment by michaelsoren** [comment]
Ah, first question was answered already, never mind.

**Comment by susanstevens** [comment]
We won't hold it against you that you completed an extra section of the tutorial! No need to roll it back.
