### ISSUE TITLE
Question about "Private" repositories

### ISSUE THREAD

**Issue by firegolza** [uchicago-mobi/MPCS51030-2019-Winter-Forum#13]
Dear Ms. Stevens,

I recently committed both the tutorial and the playground, but I am worried about the "private" marker on top. Can you still access the repository? Thank you!!

Sincerely,
Alexander Pietraszek

**Comment by hbennett766** [comment]
The private marker is correct. All of the instructors will be able to access students' repositories, but students are prevented from accessing other students' projects and grades.

**Comment by hbennett766** [comment]
(To directly answer your question, we can see your repo for assignment 1. I just checked!)
