### ISSUE TITLE
CLLocationManager: didUpdateLocation is not called

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51030-2019-Winter-Forum#130]
I have a LocationService class, which has a CLLocationManager called locationManager.

I set locationManger's delegate and:
`locationManager.requestAlwaysAuthorization()`
`locationManager.requestWhenInUseAuthorization()`

 in the constructor.

I call `locationManager.startUpdatingLocation()`

I set Privacy Always in Use/ Always and When in Use/ When in Use keys in info.plist.

I tested in both the simulator and my iPhone, changing locations multiple times on the simulator.

And yet, `didUpdateLocations` and `didFailWithError` are never called--I can't figure out why.

Code is up to date in my repo, see Utilities/LocationService.swift

**Comment by hbennett766** [comment]
Try deleting the app from both the phone and the simulator, and relaunch the app from ground zero. Sometimes if the app is already installed when you add those provacy keys, it doesn’t go through with the request.

**Comment by lmnoel** [comment]
No luck

**Comment by hbennett766** [comment]
Ok, I'll take a look

**Comment by hbennett766** [comment]
There's a bit of an architecture mixup. You do a great job encapsulating your code into classes and files. Tucking the location code into a Location Service is a great idea. However, think about the delegate methods you're calling, `didUpdate` and `didFail`. The class that signs up as the delegate, `MasterViewController`, is going to be the one receiving these calls, not the delegate object itself. Move those delegate methods into an extension in the view controller, and you should be good to go.

**Comment by lmnoel** [comment]
That did the trick, thank you!
