### ISSUE TITLE
Making collectionView visible under detail view not working as session notes described

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#136]
So I am following the instructions from session note 6 to create a "clear background" for my detail view. but it is not displaying as expected. The transparent part will display the background tab bar view for a second but then disappeared. 

[screen recording for the problem.mov.zip](https://github.com/uchicago-mobi/MPCS51030-2019-Winter-Forum/files/2953404/2019-03-11.12.09.21.mov.zip)
Please see that right after the view is presented, the root disappeared.
Any idea why that happened? Thanks!

**Comment by chelseatroy** [comment]
Yes—through the clear background you can see the tab bar on the view underneath the detail view before that view disappears. 

Are you wanting the tab bar to be available from your detail view, or are you wanting the root view to stay visible underneath the detail view?

**Comment by JohnReddyZhang** [comment]
I just want it to stay visible, like a background image. But now it disappears after segue

**Comment by JohnReddyZhang** [comment]
In current implementation, that view does not attempt to show things below it, since there were basically nothing to show.
