### ISSUE TITLE
Settings not displaying

### ISSUE THREAD

**Issue by firegolza** [uchicago-mobi/MPCS51030-2019-Winter-Forum#137]
So I am attempting to display the date (MM/dd/YYYY) for the first time the user opened the app. It is correctly assigning the date (I know by printing), but it is not displaying it in settings! It is only displaying
 "Group - Date" and not "Title - MM/dd/YYYY". Here is my code:

```
        let currentCount = UserDefaults.standard.integer(forKey: "launchCount")
        if currentCount == 0 {
            let formatter = DateFormatter()
            formatter.dateStyle = .medium
            formatter.dateFormat = "MM/dd/YYYY"
            let initialOpenDate: Date = Date()
            let date = formatter.string(from: initialOpenDate)
            openDate = date
        }

        guard UserDefaults.standard.string(forKey: BingoUserDefaultsKey.date.rawValue) == nil else { return true }
        let initialDefaults: [String : Any] = [
           BingoUserDefaultsKey.date.rawValue : openDate
        ]
        
        UserDefaults.standard.register(defaults: initialDefaults)
        return true

enum BingoUserDefaultsKey: String {
    case date
}
```

"Root.plist"
```
	<array>
		<dict>
			<key>Type</key>
			<string>PSGroupSpecifier</string>
			<key>Title</key>
			<string>Date</string>
		</dict>
		<dict>
			<key>Type</key>
			<string>PSTitleValueSpecifier</string>
			<key>Title</key>
			<string>MM/dd/YY</string>
			<key>Key</key>
			<string>date</string>
		</dict>
	</array>
```

How do I fix this?
Thanks!

**Comment by chelseatroy** [comment]
Hi Alex,

What file and method is that first chunk of code in, and where in your project does the `BingoUserDefaultsKey` live?

**Comment by firegolza** [comment]
The first chunk of code exists in "AppDelegate.swift" within the method    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool { }. BingoUserDefaultsKey is in a separate file called "BingoUserDefaultsKey.swift" where the key is a struct.

**Comment by chelseatroy** [comment]
OK. Trying to pull down your project and look, but I don't see it. Is it pushed?

**Comment by firegolza** [comment]
I will push it right now.

**Comment by firegolza** [comment]
Managed to fix it myself. Thank you for offering to help!
