### ISSUE TITLE
Additional Office Hours on Sunday Afternoon, March 17, 3-5 PM in Crerar

### ISSUE THREAD

**Issue by chelseatroy** [uchicago-mobi/MPCS51030-2019-Winter-Forum#144]
Exact location TBD (but probably on the second floor of Crerar in that common area)

Feel free to come with questions about:

- Your final project: features you're working on, stuff you're struggling with, et cetera
- Android vs. iOS: questions about how the frameworks differ and how you might feel about Android
- General job questions: No guarantees, but if you're looking, I'd like to know that

**Comment by chelseatroy** [comment]
Update: The hours will be 3-5 PM. 

We'll do this on the second floor of Crerar in the common area to the left of the front door.

**Comment by jarofmy** [comment]
Will Hannah still be hosting office hours in the loop?

**Comment by hbennett766** [comment]
Yep 👍🏻
