### ISSUE TITLE
Stack view items overlapping

### ISSUE THREAD

**Issue by skoop12** [uchicago-mobi/MPCS51030-2019-Winter-Forum#145]
I am trying to make the content of my view fill the screen proportionally no matter the device size, so I embedded the vertically aligned views in a stack view, but when I run it in the simulator the content of the some of the views is getting pushed on top of each other. I have the spacing of the stack view set to 8, so I can't figure out why it's pushing some of the views on top of each other. Any ideas of how to fix this?

**Comment by hbennett766** [comment]
You've got some storyboard layout issues going on. Note the layout warnings telling you various objects are misplaced or ambiguously positioned within some of your view controllers.

The layout ability of a stack view is to arrange its direct children in a single direction. In your view controller, you've added a regular uiview to a stackview, and then add subviews (get weather button, temp image, temp label) inside that uiview. These subviews are the _grandchildren_ of the stackview, and will not be autolayed out for you. If you want them to not overlap, you'll either need to replace the uiview with a horizontal stackview, or set constraints inside the uiview.

Lmk if this makes sense!

**Comment by skoop12** [comment]
That helped thanks!
