### ISSUE TITLE
Nested View Controller is not initialized correctly during UIApplicationShortcutItem Quick Action

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51030-2019-Winter-Forum#149]
I'm trying to add a UIApplicationShortcutItem/3d Touch Quick Action/whatever it is called, which takes the user to a nested view controller off of the root view controller in my app. In AppDelegate, If the "AddWaypointAction" shortcut item occurred, I set a boolean in my root view controller to segue to the desired nested view controller after `viewDidLoad` has finished on the root view controller.  (<-- I'm sure there is probably a much more elegant way to accomplish this, my code seems far too complicated-- see lines 66 onward in AppDelegate)

Then, if the boolean is set, I segue to AddWaypointViewController at the end of `viewDidLoad` in the root view controller. 

This works if the app is running in background when the user calls the shortcut. If the app is not running, however, it seems that view controllers get pushed to the navigation item out of order and everything gets messed up. 

How can I fix this problem? Thanks! (Latest code is pushed to repo)

**Comment by chelseatroy** [comment]
Hi Logan,

OK, looking at the project. I think I'm a little confused re: what you're trying to do. So as a user, when the app isn't running, what should I do on the phone to trigger the behavior you're describing?

**Comment by lmnoel** [comment]
Yeah, I understand why you are confused--The app should open to the nested AddWaypointView in both cases: if the app is already running, and if the app is not already running.

**Comment by chelseatroy** [comment]
Gotcha. Forgive my ignorance—under what circumstances should it _not_ open right to that view? Because if there are none, then that should be the initial view controller.

**Comment by lmnoel** [comment]
If the user opens the app normally, it should open to MasterViewController--the root view. If the user selects the Add Waypoint Force Touch Shortcut, the app should open to the AddWaypointViewController.

**Comment by chelseatroy** [comment]
AHHHHHHHHH. Okie doke, _now_ I understand. Let me look a little closer and get back to you in a bit! 

(And if this isn't working by tomorrow, I'll be on campus by 3PM and we can look at it together then)

**Comment by lmnoel** [comment]
Thanks!

**Comment by lmnoel** [comment]
Fixed
