### ISSUE TITLE
iPhone has denied the launch request

### ISSUE THREAD

**Issue by carterperrin** [uchicago-mobi/MPCS51030-2019-Winter-Forum#150]
Is anyone else running into the `iPhone has denied the launch request.` error when trying to run their applications in debug mode on an actual device? The issue is described on the Apple developer forums [here](https://forums.developer.apple.com/thread/114647) and [here](https://forums.developer.apple.com/thread/114731).

I haven't been able to find a workaround to use an actual device for development purposes 😭. It also does not appear to be related to my app, as I'm getting the error when trying to run other applications (even for a brand new project). 

I'm running iOS 12.1.4 on my device and version 10.1 of Xcode.

**Comment by carterperrin** [comment]
Unfortunately, the only thing that resolved this for me was upgrading to a paid developer account.

**Comment by susanstevens** [comment]
Someone else had this issue at office hours on Saturday. We were able to monkey around with certificates a bit, and get the app to at least run on a device. But it only worked if we deleted the app between each run. So unfortunately, I don't have a good solution (other than upgrading to a paid account).
