### ISSUE TITLE
Segue to black screen

### ISSUE THREAD

**Issue by skoop12** [uchicago-mobi/MPCS51030-2019-Winter-Forum#155]
I found a weird bug while testing my app and I'm having trouble figuring out what the cause is. On my "AllSetViewController" there is a "Back to Weather" button at the bottom of the screen that pops the user back to the root view controller (the main weather screen). Usually this works correctly, but I found that if I click the button too quickly it sometimes navigates to a black screen and from there the app can't be used unless I quit out of it. Any ideas of what is causing this or how to fix it?

**Comment by chelseatroy** [comment]
Weather Dresser 3 is the folder for the latest, right?

**Comment by skoop12** [comment]
Yes!

**Comment by chelseatroy** [comment]
OK 1 sec

**Comment by chelseatroy** [comment]
Ok, managed to reproduce. Now looking at reasons

**Comment by chelseatroy** [comment]
OK, it only seems to happen the first time I run your app (as in, I delete it from the device, reinstall it, and then click the button after the text animating downward has started but before it has finished). Are you getting that same behavior?

**Comment by chelseatroy** [comment]
Oh. 

So here's what's happening:

**Comment by skoop12** [comment]
That makes sense! Thanks for the detailed explanation
