### ISSUE TITLE
Mocking system time for testing

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#157]
My app should trigger an action at midnight every day. Is there an easy way to mock the system time in simulator so that I can test this?

Looking online, the only answer I'm finding is to change the system time on my Mac before running the app. That's less than ideal, so I wanted to check here if anyone knows a better solution.

**Comment by susanstevens** [comment]
This is a situation where I might add a "developer" section to my settings bundle (and of course remove it for actual release builds). 

There are a few ways a settings bundle could help you here. You could have a text field to enter in a fake time and a toggle that tells your app when to use the real time and when to override it with the fake time. Then you would have an if-statement somewhere in your code checking the value of that toggle and overriding the real time with the fake time if needed. (There might be other, better solutions, too, depending on how your code is set up.)

I agree with you that changing the system time on your Mac sounds like a not-great idea.

**Comment by ab1470** [comment]
Thanks! It would be nice if there were an easy way to mock the system time in the simulator. Maybe in a future version of Xcode...
