### ISSUE TITLE
Asset catalog displays as folder

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#19]
I'm not sure what I did, but my Asset Catalog now displays as a folder. Any idea how to restore the asset catalog to its normal state?

<img width="218" alt="screen shot 2019-01-18 at 4 10 33 pm" src="https://user-images.githubusercontent.com/22333279/51415584-eb86a100-1b3b-11e9-9ac5-ffe183941cb7.png">

**Comment by susanstevens** [comment]
I would try deleting Assets.xcassets, and selecting "Remove Reference" (**not** "Move to Trash") on the pop-up that appears. Then you can right-click on one of your other files and select "Show in Finder". Assets.xcassets should be there in Finder as well, and you can drag it back into the navigation panel in Xcode. Make sure that "Copy items if needed" is checked.

Let me know if that works!

**Comment by ab1470** [comment]
It worked! Thank you.
