### ISSUE TITLE
Chelsea Troy's Office Hours are Virtual This Week!

### ISSUE THREAD

**Issue by chelseatroy** [uchicago-mobi/MPCS51030-2019-Winter-Forum#26]
Hi all!

I am out of town this week, so my office hours will be virtual. 

I had originally posted a video chat link for this, but then I realized that the video chat service has a time limit for calls 😫SO, instead, please send me an email at heychelseatroy@gmail.com or text me at 646 727 0791, and we can hop on a chat as necessary or resolve it asynchronously.

**Comment by tieyong** [comment]
Hey Chelsea,
I actually had a question with my grade for HW1. I did make a post in our forum at (https://github.com/uchicago-mobi/MPCS51030-2019-Winter-Forum/issues/16) but the post was closed.  I guess why you didn't see it while grading my homework. Can I get my points back for that?
Thanks a lot.

**Comment by JohnReddyZhang** [comment]
I haven't received grades for last week yet... Should I expect it to come out tomorrow? Thanks!

**Comment by hbennett766** [comment]
Grades are posted to a “grade” branch. Switch from master to grade to view the rubric and comments.

**Comment by tieyong** [comment]
@chelseatroy I saw the grade update. Thanks a lot!
