### ISSUE TITLE
Case Studies

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/MPCS51030-2019-Winter-Forum#27]
Hey everyone! I know we didn't get to talk about the requirements for case studies this week, but I do want you to start thinking about what app you'd like to present on and find a partner to work with. 

As part of the assignment this week, please fill out this [google form](https://docs.google.com/forms/d/e/1FAIpQLSciH-UGT1UNvVFpO8jRwio3ZPXWdOvLD--aySD4YkHGbNMzEg/viewform) with your name, your partner's name, the app you'd like to present on and two dates that work for you. Each pair only needs to fill out the form ONCE (i.e., each person does not need to fill it out separately).

Requirements for case studies are [here](http://uchicago.mobi/case-studies/), although we will talk more about them next week.

Also, if you are looking for a partner, feel free to post a comment on this thread so that you can find someone to work with.

**Comment by michaelsoren** [comment]
Hey, I'm a BS/MS undergrad looking for a partner. I would like to do the case study during or after 7th week. Just email me at michaellemay1@me.com.

**Comment by JohnReddyZhang** [comment]
Hi all, my name is Zhenghong Zhang and I am looking for partners to do case study as well. Since I am graduating this quarter I would like the case study presentation to be earlier. 

I am interested in doing a  health app related to fitness like NTC, NRC, Keep, or to sleep monitoring like SleepCycle, AutoSleep, or to meditation like Headspace. 

Please contact me at zhzhang135@uchicago.edu if you are interested! Thank you!

**Comment by jiseung** [comment]
Hello! My name is Anna, and I'm also looking for a partner. I'm free for any of the case study times, and although I'm personally interested in productivity apps, I'm open to do a case study on an app that I don't have much familiarity with. My email is jiseung@uchicago.edu if you're interested. Thanks!

**Comment by peterwang0531** [comment]
Hello, I'm Junhao Wang, looking for partner.  I'm interested in some social media apps, but still open to other apps for case study. contact me via jhwang96@uchicago.edu if you are intereste

**Comment by jbreynier** [comment]
Hi! I'm JB, I'm also looking for a partner for the case studies. I'd be interested in productivity apps or social media apps, but I'm also open to other ideas! You can email me at jbreynier@uchicago.edu

**Comment by jarofmy** [comment]
Hi, my name is Jeremy. A little bit about myself: I enjoy running, puzzles, ping-pong, league of legends, music production, and Bob Ross.

I'm hoping to do a case study on the Slack app (with competitors such as WhatsApp, GroupMe, etc.) If anyone would be interested in working together on this, please feel free to email me at jeremyvan@uchicago.edu
