### ISSUE TITLE
Where should networking code live? And also Model-View-Controller architecture

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/MPCS51030-2019-Winter-Forum#31]
Question posed: After modifying line 1-49 in MPCS51030-2019-Winter-Forum/Session3-Networking.playground/Contents.swift, where should we place them?

**Comment by hbennett766** [comment]
You should place them where it fits best for your app. It's really up to the developer. I am personally a big fan of code encapsulation, both in regards to files and methods. Therefore, I don't think you should paste this block into `viewDidLoad()`. You could create a separate networking file and class, e.g. `NetworkingController`. You could create an extension on your view controller. You could mark the method and leave it in the main part of your view controller declaration, e.g. `// MARK: Networking`. It would also be a good idea to create a separate file, or files, for your `struct`s. This follows [MVC (Model View Controller)](https://www.raywenderlich.com/1073-model-view-controller-mvc-in-ios-a-modern-approach), which is good architecture practice.

**Comment by hbennett766** [comment]
Also, please don't confuse "don't paste this block into `viewDidLoad()`" with "don't call this block in `viewDidLoad()`".

**Comment by susanstevens** [comment]
Piggy backing on Hannah's post about networking... There were a few questions during office hours today about what to do once you've retrieved movie data. The code from the playground just prints out the number of items retrieved, but you will need to do more than this. You'll want to 1) save the movies retrieved to an array on your table view and 2) reload your table view.

So your code in `viewDidLoad()` should look something like this:

```swift
movieService.search(for: searchTerm, completion: { movies, error in
    guard let movies = movies, error == nil else {
        print(error ?? "unknown error")
        return
    }
    print("Movies fetched: \(movies.count)")
    // 1) save movies to an array on your table view controller
    // 2) reload your table view
})
```

Conveniently, table views have a method called `reloadData()` that will trigger your `UITableViewDataSource` methods to be called again.
