### ISSUE TITLE
Navigation Bar Controller Title

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#32]
Under "Navigation controllers," the assignment says "The title of each bar should reflect the search term for the movies being displayed." However, the screenshot provided does not show any text in the navigation bar area for the Navigation Controllers.

The title appears in the TableViewControllers that follow. Should we have the title in both the Navigation and TableView controllers?

**Comment by susanstevens** [comment]
Good question! The title should be in the navigation bar that appears at the top of the table view controllers. It should match the screenshot of the storyboard.

I will update the assignment write-up to clarify that.
