### ISSUE TITLE
Power strips for Ryerson 251

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/MPCS51030-2019-Winter-Forum#33]
There was a request last session to get some power strips and extension cords for the classroom, since Xcode can be a bit draining on laptop batteries. Since Ryerson isn't a CS building, we can't leave power strips there, but the department can have someone bring them to the classroom on Wednesdays before class.

**However, we would need a volunteer to take the power strips and extension cords back over to Crerar after class each week.** Is anyone able to do this? Please reply to this thread if you want to volunteer! Otherwise, we can keep making using of the wall outlets during breaks.

**Comment by liuwinshen** [comment]
Thanks, Susan. Is it possible to ask the Math department if we can keep extension cords in the classroom (perhaps in the podium) just until the end of the quarter? I don't imagine they'll take up much space.

**Comment by susanstevens** [comment]
@liuwinshen I don't think so, unfortunately. It sounds like the department needs them to be returned to Crerar after class.
