### ISSUE TITLE
Code seems to run fine, but no cells appear in table cell slots

### ISSUE THREAD

**Issue by michaelsoren** [uchicago-mobi/MPCS51030-2019-Winter-Forum#35]
So I have written up the table view controller and the code seems to run fine in the debugger (it creates the table with no crashes). I've implemented the three data source methods in the table view controller. The reuse identifiers are all set. I have the data loaded and when I print the data, I can see that it is there. But when I run the simulator, I get this.

![image](https://user-images.githubusercontent.com/25490468/51807664-9c352480-224f-11e9-9232-516f8170d2a7.png)

Any ideas why this is happening?

**Comment by susanstevens** [comment]
Are you calling `tableView.reloadData()` after your movies are returned from the network request? Take a look at [this comment](https://github.com/uchicago-mobi/MPCS51030-2019-Winter-Forum/issues/31#issuecomment-457875345) and make sure your code matches.

You could also put some print statements in your three data source methods to see if you have data when they are called. (They will be called at least once before your network request completes. But they should be called _again_ after it completes and you have data present.)

**Comment by susanstevens** [comment]
Yep, what you have looks right. I wonder if something else is going on. If you're comfortable using breakpoints in Xcode, you could try setting some in your data source methods and stepping through your code. Or you could try putting print statements in a few more places to debug.

I would focus on investigating your `cellForRowAtIndexPath` method. Is the cast to `MovieTableViewCell` failing? Are your labels nil?
