### ISSUE TITLE
** No Class This Wednesday (Jan 30) **

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/MPCS51030-2019-Winter-Forum#38]
Everyone has probably seen the [announcement](https://news.uchicago.edu/story/classes-canceled-jan-30-due-extreme-weather) that classes will be cancelled this Wednesday due to the extreme low temperatures. Here are a few announcements in light of the cancellation:

1. We'll have a **make-up session** later in the quarter. I will send out a survey later with a few possible dates and times, but plan for the make-up session to be held on a Saturday or Sunday.

2. **Case study presentations still need to start on Wed, Feb 6.** I will send out the schedule for case studies later this week, so make sure you find a partner and fill out the [sign-up form](https://docs.google.com/forms/d/e/1FAIpQLSciH-UGT1UNvVFpO8jRwio3ZPXWdOvLD--aySD4YkHGbNMzEg/viewform).

3. **The deadline for this week's homework is extended to midnight on Wed, Jan 30.** Since you're missing out on our class session this week, you can spend some extra time polishing your movies app if you like. 😃 Plan for Chelsea's office hours to be held **remotely** at the usual time.

Lastly, please stay safe in this cold and snowy weather!

**Comment by skoop12** [comment]
Is there any way to have class virtually on Wednesday rather than reschedule? (Asking because there are already two other MPCS classes that meet on Saturdays)

**Comment by lmnoel** [comment]
Second the idea of a virtual class. Maybe a video lecture?

**Comment by susanstevens** [comment]
It's important for this next class to be held in-person. It's difficult to participate and ask questions virtually, and I want everyone to feel prepared for the next homework assignment.

I know that it will be difficult to find a weekend time that works for everyone. I'll record the make-up session and post the video for anyone who isn't able to attend. And there will not be a homework assignment associated with that session.
