### ISSUE TITLE
Trouble creating IBOutlet for UITextView

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#39]
How are UITextViews different from labels when connecting them to IBOutlets?

I keep getting errors when I try to connect my storyboard TextView to MovieDetailViewController either as a weak or strong var. I've tried to do permutations with String as the type given the error messages but to no avail.

![screen shot 2019-01-29 at 8 17 13 am](https://user-images.githubusercontent.com/35438782/51917238-bb919600-23a4-11e9-958d-264726b0d4f9.png)

**Comment by hbennett766** [comment]
You can't name anything that is already a reserved keyword in Swift. `description` is one of those keywords. Delete that property in code, and also remove the connection in storyboard. Then re-connect using a different name, such as `textView`.

**Comment by liuwinshen** [comment]
Oh, I see. Thank you!
