### ISSUE TITLE
Autolayout Failed

### ISSUE THREAD

**Issue by binwei-yu** [uchicago-mobi/MPCS51030-2019-Winter-Forum#41]
I create a stack view for labels in a cell. But whatever number I set for the horizontal position constraint, the stack view always positions in the most left. Secondly, after setting up constraints, the labels are unable to truncate text tails. I attached two pictures with this post.
<img width="871" alt="2019-01-29 12 07 02" src="https://user-images.githubusercontent.com/28250445/51929740-8e51e180-23be-11e9-8f5d-89b364527769.png">
<img width="335" alt="2019-01-29 12 07 26" src="https://user-images.githubusercontent.com/28250445/51929746-91e56880-23be-11e9-91eb-9db03f087288.png">

**Comment by susanstevens** [comment]
A stack view manages the layout of the views it contains, so it's typically not necessary to set constraints between views that live inside a stack view. I would try setting fixed height and width constraints on the items inside the stack view, and removing any constraints between the views.

We'll talk more about stack views in a future class, but you could also take a look at [this tutorial](https://www.raywenderlich.com/508-uistackview-tutorial-introducing-stack-views) if you want to learn more about how they work.
