### ISSUE TITLE
Passing a movie object to detail view

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#44]
Hi! I am think of passing the movie object queued from the movies list to the details page using `prepare(for segue)`, but as indicated in class, it seems that we should have a dummy object in the detail view controller to accept the data coming from the prepare function (just like the "time string" in demo in class)

However with the struct of Movie object, I could not just have a `var currentMovie = Movie()` in the detail view controller. What is a proper way of passing the data (or to say let the detail controller be ready to accept the data coming from its previous scene?) I don't think setting each property of the destination in the prepare function is a good choice here...

Thank you very much!

**Comment by susanstevens** [comment]
This is a great question. You're right that it would be cumbersome to pass each property on your movie object individually to the detail view controller. And unlike string, which has `""` as a reasonable default value, `Movie` doesn't really have a good default to set on your detail view controller before real data is passed to it.

This is a situation where optionals come in handy. If you make `var currentMovie` an optional, then its default value can be nil. When `prepare(for segue: sender:)` is called, you can give the `currentMovie` property a (non-nil) value.
