### ISSUE TITLE
Adding UIBarButtonItem to the detail view controller’s navigation item result in "Toolbar Items"

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#46]
Hi!
I am working on the assignment about adding a UIBarButtonItem to the detail view controller’s navigation item. However, in the current storyboard (similar to the screenshot given), when I drag the UIBarButtonItem to that view it could only be added as an item under "Toolbar Items".
<img width="319" alt="2019-01-30 1 53 42" src="https://user-images.githubusercontent.com/15935574/51966375-f1c92700-2431-11e9-8073-c26e5c07ceae.png">

Embedding in "Navigation Controller" will result in the data not being able to be passed (and animation becomes from bottom up), 
<img width="392" alt="2019-01-30 1 54 34" src="https://user-images.githubusercontent.com/15935574/51966445-20470200-2432-11e9-97bd-323d0b171139.png">
<img width="308" alt="2019-01-30 1 55 19" src="https://user-images.githubusercontent.com/15935574/51966446-20470200-2432-11e9-95cb-7e85b25e8860.png">

and just adding a "Navigation Bar" to the view's top result in the navigation bar being blocked.
<img width="403" alt="2019-01-30 1 56 19" src="https://user-images.githubusercontent.com/15935574/51966485-42408480-2432-11e9-9737-0ed7057c403e.png">

What is a proper way of doing this? It there anything wrong I did in the previous steps that resulted in not having a navigation in Details page?
Thank you very much!

**Comment by hbennett766** [comment]
Another student also had this issue in storyboard. You could always do it [programmatically](https://www.hackingwithswift.com/example-code/uikit/how-to-add-a-bar-button-to-a-navigation-bar). As with any `#selector`, you'll have to add an `@objc func myMethod()` to your detail class in which to perform the desired actions.

**Comment by chelseatroy** [comment]
Hi!

The above is a bit of a known issue in XCode :( concur with Hannah. The programmatic method, for now, is more robust.

**Comment by JohnReddyZhang** [comment]
I achieved similar results by adding "Navigation Item" then added the BarButtonItem to that. On storyboard it has an extra "Title" section displayed, but looks like that does not really affect functionality. 
Also, will we talk more about opening an URL etc. in next lecture? I could open the url in Safari app but I am wondering how to open that URL within the app using the "simplified Safari-like" view (like the screenshot below taken from reddit app), however not sure what should be the keywords to google for that...

![img_5010](https://user-images.githubusercontent.com/15935574/51999816-3af49780-2481-11e9-898d-744f8cc8163b.PNG)

**Comment by hbennett766** [comment]
Also, here’s a good tutorial on a simple way of presenting web views: https://www.talkmobiledev.com/2016/12/04/opening-a-url-through-sfsafariviewcontroller/

Is this the same or different from what you’re currently doing?

**Comment by JohnReddyZhang** [comment]
Yes, that one is what I am looking for! Thank you very much!
