### ISSUE TITLE
"Learn the Essentials..." exercises

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#5]
Part of the assignment for this week is to "Read and complete the exercises in the Learn the Essentials of Swift playground."

By "complete the exercises", do you mean that we should answer all of the questions with the "Experiment" label? 
<img width="619" alt="screen shot 2019-01-12 at 1 32 52 pm" src="https://user-images.githubusercontent.com/22333279/51077618-ca6f0d80-166e-11e9-9c7c-ce20b273a989.png">

If so, how do you want us to submit our answers? (PDF, .txt, .playground... ?)

**Comment by susanstevens** [comment]
You don't need to submit written answers to any of the questions, just try out the experiments. You can always change the code back to something that compiles if the experiment has you do something that results in a compiler error. When we grade the assignment, you'll get credit as long as we see changes in the playground, showing that you've read through it and played around with some of the code.
