### ISSUE TITLE
Views overlapping incorrectly

### ISSUE THREAD

**Issue by michaelsoren** [uchicago-mobi/MPCS51030-2019-Winter-Forum#51]
I've searched around a bit on the internet and I'm not quite sure how to fix an issue like this/set a precedence ordering for the views.

![image](https://user-images.githubusercontent.com/25490468/52435249-fc8d5700-2ad6-11e9-9dbe-76e1507e0a56.png)

**Comment by susanstevens** [comment]
Good question! You can rearrange the views in the Document Outline (the panel on the left side of the storyboard, highlighted in the screenshot). The view at the very bottom of the list will appear *above* all other views. And the view at the very top of the list will appear *below* everything else.

Every once in a while, rearranging views this way doesn't actually seem to change the order in which they appear on the simulator, even though it should. When this happens, I'll try to rearrange again and re-run. Or delete the view and add it back to the storyboard.

<img width="1440" alt="screen shot 2019-02-07 at 6 23 16 pm" src="https://user-images.githubusercontent.com/10423328/52451740-d59a4980-2b05-11e9-9f8a-b3bc31f81232.png">

**Comment by michaelsoren** [comment]
Thanks!

**Comment by JohnReddyZhang** [comment]
Found this when I was about to ask the same question... This looks very counter-intuitive...
