### ISSUE TITLE
Grid and moving x and o pieces 

### ISSUE THREAD

**Issue by eealexander2** [uchicago-mobi/MPCS51030-2019-Winter-Forum#56]
I am not quite sure why this happens, but when I adjust the grid in storyboard and then test it out in simulator my X and O pieces sometimes go under the grid and disappear, instead of on top of the grid. Any ideas why? Thank you!

**Comment by hbennett766** [comment]
This may be the same view overlapping issue as #51. Does this solve your problem?

**Comment by eealexander2** [comment]
Well, sometimes the pieces go on top of the grid and other times they don't, it doesn't really seem to be consistent. Should the 9 tile views be nested under Grid View? I have them nested but maybe shouldn't.

**Comment by eealexander2** [comment]
follow up to that - I am unable to make the squares not "subviews" of the grid view in storyboard. I drag them out from the Grid View "Directory" in storyboard but they snap back as subviews. Any ideas?

**Comment by hbennett766** [comment]
Whether they're nested is up to you. Off the top of my head, I'm not sure why they'd be snapping back into place. If you have layout constraints set up, that could be the reason. Can you push your code to your repository? This will be quicker to diagnose if I can see what's going in.

**Comment by eealexander2** [comment]
Thanks for the info. I decided instead to programmatically set the frames of each square and that seems to be working. Thank you!
