### ISSUE TITLE
How to add gesture recognizers to new pieces

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#58]
I have an IBAction called xPan that has a UIPanGestureRecognizer sender. I am having trouble adding this to the newly generated game piece. I've tried the following and would appreciate any guidance!

1. addTarget
Swift tells me I can't call this on an UI Image View...
![screen shot 2019-02-11 at 11 43 54 am](https://user-images.githubusercontent.com/35438782/52582378-b4ca4080-2df2-11e9-823a-b0b1b90ea12a.png)

2. addGestureRecognizer
Swift tells me xPan isn't the right type. How can I convert my IBAction to the right type for this to work?
![screen shot 2019-02-11 at 11 40 52 am](https://user-images.githubusercontent.com/35438782/52582135-1a69fd00-2df2-11e9-88cc-31581a81184d.png)

**Comment by hbennett766** [comment]
In the line above your errors, you're setting user interaction to `false`. That needs to be `true` for gesture recognizers to work.

**Comment by liuwinshen** [comment]
Yes, but these errors appear even if user interaction is enabled.

**Comment by hbennett766** [comment]
It looks like `xPan` is the method that gets called to do the panning. That method is different than the gesture recognizer itself. Create a new instance of a pan gesture recognizer, 

`let panGestureRecognizer = UIPanGestureRecognizer(target: self, action: #selector(<some @objc method>))`

then add that new instance of the tap gesture recognizer to the player, via the `addGestureRecognizer` built-in method you have in your option 2.

**Comment by liuwinshen** [comment]
Thanks, @hbennett766! This makes sense and I'll give it a try.

My takeaway is that gesture recognizers for this are attached to a single item rather than reused. Even if the new piece's panning is the same as all the pieces before it, I need to create a new one for it rather than use the one created as an IBAction. Let me know if that's not accurate!

**Comment by hbennett766** [comment]
I _believe_ the gesture recognizer instance can be reused. I am under the assumption that xPan is a method, an action of some sort. The gesture recognizer and the action it invokes are two separate objects, that was my only point. The addGestureRecognizer method needs an instance of a gesture recognizer. And within that instance, you declare the method that the recognizer calls. Does this line up with your thought process?

**Comment by liuwinshen** [comment]
Ah, I see. Your point that the gesture recognizer and the action it invokes are separate objects clarified my confusion! Thank you =)

**Comment by hbennett766** [comment]
Awesome, glad it makes more sense!
