### ISSUE TITLE
Return X/O token to origin

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#59]
I've spent a lot of time trying to figure out a good way to return the X/O tokens to their respective origins when the user tries to make an invalid move. My thought was to create Token.swift as a subclass of UIImageView, so that when I initialize a token I can store its origin as a property of the class. This way, I don't have to store the origin as a separate variable in ViewController.swift. Then when the user makes an invalid move, I simply call returnToOrigin().

Subclassing UIImageView turned out to be more complicated than I thought it would be, so now I'm questioning this approach. I'm also unsure of how subclassing will work in conjunction with Interface Builder (i.e., if I draw a Token in Interface Builder, can I store its position as drawn into the 'origin' property in my class? Or do I have to explicitly initialize the Token and its 'origin' property in ViewController.swift?)

**Comment by hbennett766** [comment]
This page of the Apple docs has some good sample code. It demos one way (of many) to keep track of the piece’s starting point. Does this help in your case?

https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/handling_uikit_gestures/handling_pan_gestures

**Comment by ab1470** [comment]
Got it, thanks!
