### ISSUE TITLE
Positioning Info View

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#61]
I am not sure whether I am doing this right or wrong...
When I create the infoView, I drag the UIView into the storyboard and try to place it at the center of the screen (it should snap to the center). However when I try to move the view to center it keeps going to be child views of the square view (like in the screenshot)
<img width="1440" alt="2019-02-11 7 16 14" src="https://user-images.githubusercontent.com/15935574/52604704-9f283b80-2e31-11e9-9d78-188dd6f2462f.png">

Is there a way to temporarily "hide" the grid view in the back so that I could find the right place for the info view (my idea is to place InfoView in the center position and then get its x and y coords for the animation)? Or am I supposed to make it appear totally programmatically?

Thank you very much!

(Also if you look at my storyboard there is a toolbar on the bottom of screen which appeared because I dragged a BarButtonItem to the View by fault. Is there a way to remove that? I have tried removing the barButton and restarting Xcode it did not went away...)

**Comment by susanstevens** [comment]
If you're having trouble positioning a view without storyboard making it a subview of another view, I would recommend setting the x and y coordinates in the Size Inspector (fifth tab in the right panel in storyboard).

To remove the tool bar, try selecting your view controller in storyboard and opening the Attributes Inspector (to the left of the Size Inspector). The third drop-down is called "Bottom Bar". If you select "None", the tool bar should go away.

**Comment by JohnReddyZhang** [comment]
Thank you for that! I also set the center of the infoView to out of screen in ViewDidLoad. It seems to work as well!
