### ISSUE TITLE
Question About End of Turn

### ISSUE THREAD

**Issue by szhou12** [uchicago-mobi/MPCS51030-2019-Winter-Forum#62]
Hi! 
I'm working on the End of Turn part of the game. After using the pan gesture to put a piece into a grid, I was wondering how we could display a new piece for the next turn? For example, suppose I used UILabel for the X piece and in the end state of the pan gesture, I moved it into one of cells in the grid, how can we prepare for a new X piece that inherits the connection with the UILabel? I've been stuck in this part for quite long and couldn't figure out a proper way to address this issue. Any suggestions would be appreciated!

Thank you!

**Comment by hbennett766** [comment]
You don't need to inherit any connection with the storyboard, and IMO, you shouldn't try to do that. The only information the new label needs is its starting frame (same as the original one), and the pan gesture recognizer attachment. All of that can be done programatically. Does that make sense/help you out?

**Comment by susanstevens** [comment]
Like most problems in software development, there isn't just one solution here. As Hannah mentioned, you can achieve this programmatically by creating a new label or image view and calling `view.addSubview(xPiece)`. With this approach, you'll also need to add the gesture recognizer programmatically.

You could also add several X pieces to your storyboard, one on top of the other. They could start out hidden from the user, and you could show each one when a new turn begins. In this case, you might choose to reference them through an outlet collection.

You might also think about creative ways to use your nine square views on the grid. What if your nine squares were also labels or image views? Could you have just one X piece with a gesture recognizer and reuse that piece on each new turn?

**Comment by szhou12** [comment]
Solved! Thank you!
