### ISSUE TITLE
Switching which piece has user interaction enabled

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#64]
At the end of a turn, we create a new piece, say "X," that the user cannot interact with. The other player, "O," has their piece's user interaction enabled. I understand how to enable user interaction, but only for an image view I've just created or that is connected through the storyboard.

How do I access a programmatically created UIImageView that already exists on the screen? Is it a good practice to generate unique identifiers and use that?

**Comment by hbennett766** [comment]
You could keep a reference to `var currentXPiece: UIImageView` and `var currentOPiece: UIImageView` at the class level. Then when you need to create a new piece after a turn, you just override that reference:

```
// turn ends, currentXPiece is placed
func createNewXPiece() {
    currentXPiece = // instantiate new UIImageView
   // set whatever properties you need to
}
```

This is just the first idea that came to mind. There are many ways to accomplish this. I _personally_ don't love using tags and UUIDs to identify view elements. Emphasis on "personally". Maybe other devs love them. I just think that there are cleaner and slicker ways to accomplish that identification. Lmk whether this helps.

**Comment by liuwinshen** [comment]
Thank you. I prefer your way over identifiers as well!

Since I had the starting xPiece as an IBOutlet, it's a weak var at the class level:
`@IBOutlet weak var xPiece: UIImageView!`

Seemingly I can replace its UIImageView in the same way as if it were a normal `var`? (If not, I can just programmatically create it, right?) What is the difference between strong and weak vars in Swift?

**Comment by hbennett766** [comment]
Honestly, I don't know how the program would behave if you tried to replace an `@IBOutlet` with a new reference. It's unconventional at the least. I would go the programmatic route, or another way Susan mentioned in #62. There are many ways to solve this problem!

I'm going to open a new thread for strong vs weak. That's a good question, I'd like it to be more visible to everyone else.

**Comment by hbennett766** [comment]
#66 is the expanded answer to your strong v weak question

**Comment by liuwinshen** [comment]
Thank you so much, Hannah!
