### ISSUE TITLE
submitting case study presentation

### ISSUE THREAD

**Issue by jrschaeffer** [uchicago-mobi/MPCS51030-2019-Winter-Forum#65]
How should we be submitting our case study presentation / slide deck?   I built mine in Google slides so all I Really have is a link right now.   

Is there a repo we should be committing + pushing a file / link to, or is it purely the in-person component?

Thanks for the guidance.

**Comment by susanstevens** [comment]
No need to submit slides for your case study! You'll just be graded on the presentation itself.
