### ISSUE TITLE
Who goes first?

### ISSUE THREAD

**Issue by tieyong** [uchicago-mobi/MPCS51030-2019-Winter-Forum#67]
I'm working on "the start of a turn" part. Do we need to specify who goes first ('X' or 'O')? Or the idea here is to allow either player to go first and we only need to make sure each player takes turns to make one move a time?

**Comment by hbennett766** [comment]
You should mandate the player that goes first by doing the same things you would for a regular turn, the logic behind it is the same:

- Setting the `alpha` property on the pieces
- Setting the `isUserInteractionEnabled` property on the pieces
- Performing an animation on the player's piece when it's their turn

**Comment by tieyong** [comment]
Thanks a lot!
