### ISSUE TITLE
A good solution to decide which square in grid the piece should snap into?

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#72]
Hi,
Just asking if there is some implementations of deciding which of the nine views the piece being dragged should snap into? The ideal implementation imo should be the piece snaps into the one view which has the largest overlapping area with itself. However I failed to think of a proper way to do that. Is there some suggestions on how it should be achieved (since this assignment is already passed?)

My implementation is rather simple, which just snaps into the top left (first) not occupied view. `squares` is the list of nine views, `piece` is the piece being dragged, `grid` implements some logic to decide if the view is occupied or not.
```swift
            for (index, square) in self.squares.enumerated() {
                if square.frame.intersects(piece.frame) && grid.isEmpty(in: index){
                    self.grid.markOccupied(by: self.currentPlayer!, in: index)
                    let snapInAnimator = UIViewPropertyAnimator(duration: 0.5, curve: .easeInOut) {
                        piece.center = square.center
                    }
                    snapInAnimator.addCompletion { (UIViewAnimatingPosition) in
                        // implementation of turn finished
                    }
                    snapInAnimator.startAnimation()
                 }
            }
```
I would really appreciate it if you are willing to share thoughts on better implementation, preferably still using `frame1.intersects(frame2)`. Any other suggestions on coding style is very welcome!

Thank you all very much!

**Comment by susanstevens** [comment]
Good question! In addition to the `intersect` method, which returns a bool, `CGRect` also has an `intersection` method, which returns the intersection of two rects, represented as a `CGRect`.

So you could do `let rect = square.frame.intersection(piece.frame)` and check the area of the rect that's returned to determine how much two pieces overlap. You could loop through all nine squares and find the one with the largest overlap, and then position the piece over that square.

Here's a link to the Apple documentation on `intersection`: https://developer.apple.com/documentation/coregraphics/cgrect/1455346-intersection.
