### ISSUE TITLE
If @escaping function returns something, where does the returned value go?

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#73]
Hi,
As mentioned in class yesterday, the `completion` part in `func search(for term: String, completion: @escaping ([Podcast]?, Error?) -> ())` could actually return something like (a boolean below)
```swift
func search(for term: String, completion: @escaping ([Movie]?, Error?) -> Bool) { //implementation of search
```
But the question remains: where does the returned value (here the Bool) actually go? How can that value be used?

Thank you very much!

**Comment by susanstevens** [comment]
The return value gets returned to the part of the code that actually calls `completion`. In our example, this would be inside the MovieSevice's `search` function.

```swift
func search(for searchTerm: String, completion: @escaping ([Movie]?, Error?) -> Bool) {
    
    // try to fetch movies, and when you're ready, call "completion"
    
    DispatchQueue.main.async {
        let result = completion(movies, nil) // here's the boolean being returned
        print(result) // print either true or false
    }
}

search(for: "Chicago") { movies, error in
    // do something with podcasts or error
    return true
}
```
