### ISSUE TITLE
Problem of searchBar Application

### ISSUE THREAD

**Issue by szhou12** [uchicago-mobi/MPCS51030-2019-Winter-Forum#78]
Hi!

When we used the searchBar to search for the articles, I was wondering if we were supposed to have the program keep searching while the user is typing or to only search for the keyword obtained from the user when s/he ended editing? I can make the former work by calling the searchBar() method but I guess the later one is more ideal. However, I have a trouble of realizing it as I'm trying to use searchBarTextDidEndEditing() to detect whether the user ends editing. This method seemed to never be called. 

Am I going towards a right direction or is there any better way to do it? Any suggestions would be appreciated!

Thank you!

**Comment by susanstevens** [comment]
In this case, it's definitely better to wait until the user finishes entering their search term before making a request to the iTunes API. There's a delegate method on `UISearchBarDelegate` that's called when the user taps on the search button. You can use that as your signal that they've finished entering their search term and it's time to fetch results.

You'll also need to dismiss the keyboard when the user taps on the search button. The object that's currently receiving the keyboard input (in this case, the search bar) is called the "first responder" in iOS. To dismiss the keyboard, the search bar needs to ["resign first responder" status](https://developer.apple.com/documentation/uikit/uiresponder/1621097-resignfirstresponder).

**Comment by szhou12** [comment]
Solved! Thank you!
