### ISSUE TITLE
Display Detail View First

### ISSUE THREAD

**Issue by hyangjudy** [uchicago-mobi/MPCS51030-2019-Winter-Forum#79]
Hi,

I have not implemented detail view yet, but every time I run the simulator, the detail view is displayed first. Even after I deleted the  segue from the table view cell in the master view controller to the detail view controller. 

Do you have any suggestions to solve it? Thank you!

**Comment by hyangjudy** [comment]
I just checked the iPad simulator, it works fine. But for the iPhone simulator, no matter portrait or landscape, it will display the detail view first.

<img width="909" alt="screen shot 2019-02-16 at 10 40 22 pm" src="https://user-images.githubusercontent.com/46628024/52908481-3e876d00-323c-11e9-92d8-964f97c2ac0a.png">

**Comment by susanstevens** [comment]
There's a delegate method on `UISplitViewControllerDelegate` that allows you to specify whether or not the secondary (detail) view controller should be collapsed on top of the primary (master) view controller. Returning `true` from this method tells the split view controller not to display the secondary (detail) view controller on top of the primary (master) view controller by default.

Although it's not specifically required in the assignment, if you want to make sure the master view controller is displayed first on smaller screens, you can conform to the `UISplitViewControllerDelegate` and return true from this method:

```swift
func splitViewController(_ splitViewController: UISplitViewController, 
        collapseSecondary secondaryViewController: UIViewController, 
        onto primaryViewController: UIViewController) -> Bool
```

**Comment by JohnReddyZhang** [comment]
I would like to implement this, but which `viewContorller` should I conform to this protocol? I tried extending on both master and detail view controller but nothing happens.

**Comment by susanstevens** [comment]
I would recommend having your master view controller conform to  UISplitViewControllerDelegate. Don’t forget that you will also need to set the master view controller as the split view controller’s delegate. The viewDidLoad method is a good place to do this. 

Every view controller has an optional splitViewController property that has a value if and only if the view controller is embedded in a split view controller. You can use this property to set the split view controller’s delegate.

**Comment by JohnReddyZhang** [comment]
It works now. Thank you very much! I think it's because I forgot to set delegate to self that I got it wrong before.
