### ISSUE TITLE
Warning about app icons for other platforms 

### ISSUE THREAD

**Issue by eealexander2** [uchicago-mobi/MPCS51030-2019-Winter-Forum#8]
Hello! I am getting two warnings about adding AppIcons for the iPad. Should we add an app icon for this, to dismiss the warning? Thanks so much, let me know!

**Comment by susanstevens** [comment]
You can either add icons for the iPad or change the application to be for iPhone only.


<img width="648" alt="screen shot 2019-01-13 at 8 50 07 pm" src="https://user-images.githubusercontent.com/10423328/51094732-160bdf00-1775-11e9-91fa-00bc48885d9e.png">

**Comment by eealexander2** [comment]
Oh ok, thanks!
