### ISSUE TITLE
Codable structs for nested types

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#80]
Originally, I had my structs similar to the Podcast one from the Networking example (struct NewsResult and struct Article instead of PodcastResult and Podcast).

However, when I call the News API, the JSON has the articles as dictionaries in a single array.

Thus, I am getting the error: typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "articles", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "source", intValue: nil)], debugDescription: "Expected to decode Array<Any> but found a dictionary instead.", underlyingError: nil))

How do I go from the expected `articles` dictionary to my Article struct?
```
struct NewsResult: Codable {
    let totalResults: Int
    let articles: [Dictionary<String, String?>]
}

struct Article: Codable {
    let author: String...
}
```

**Comment by JohnReddyZhang** [comment]
`let articles: [Article]` will do the trick. Also add `?` in case some keywords has zero articles.

**Comment by liuwinshen** [comment]
Thanks, @JohnReddyZhang . That's what I had originally when I got the error, so I modified articles to have a dictionary as the type.

**Comment by hbennett766** [comment]
John is correct here. When the decoder reaches the `articles` property inside your top level `NewsResult` object, it will see type `[Article]`. Th decoder will say "ok, I need to go decode a bunch of `Article` objects now." Those naming conventions is how the decoder knows where to go next with its nested object decoding. These structs need to mimic the form of the json. Hopefully that gives some insight into the "why" behind John's suggestion.

**Comment by liuwinshen** [comment]
Thanks, @hbennett766. That's exactly what I had to start, but then I got the typeMismatch error, so I was trying to fix it with matching the `articles` to `[Dictionary]`...

**Comment by JohnReddyZhang** [comment]
To debug maybe try the same query in Postman or something and see what is returned?

**Comment by hbennett766** [comment]
John is also correct in his suggestion of creating optional property types with a `?`. For two reasons:

1. We can never safely assume that this json will return each and every property type on an object. Especially because we don't control this backend. 
2. It's totally possible for an article to not have a known author.

Whatever the reason may be for a single missing property, we still want to be able to use and display the rest of the article and its existing properties. We safely account for these unknowns by allowing properties to be `nil`.

**Comment by hbennett766** [comment]
Can you post a screenshot of some sample json from this API? I don't have a key, and can't reference the structure.

**Comment by liuwinshen** [comment]
Haha, all good. Here's a screenshot of my structs and the console in case it's helpful (you can see that the results are returned fine but there is still this typeMismatch error:

![screen shot 2019-02-18 at 11 17 16 am](https://user-images.githubusercontent.com/35438782/52967162-d4231980-336e-11e9-9e93-a192134b3723.png)

**Comment by liuwinshen** [comment]
Oh, I guess it changed (I didn't have the [Article] as optional before so I guess now it's a problem with the date. Nevermind! Thank you, @JohnReddyZhang and @hbennett766 !
