### ISSUE TITLE
Blank cells randomly popping up

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#82]
Hi! I am building MasterViewController and just got the cells populating, but I keep getting Blank cells with no content in it like shown in the screenshot:
![2019-02-18 3 56 12](https://user-images.githubusercontent.com/15935574/52978258-23307500-3396-11e9-812a-3bcda813f092.png)
![2019-02-18 3 56 20](https://user-images.githubusercontent.com/15935574/52978259-23307500-3396-11e9-8005-38d0a377a68d.png)
These cells are supposed to be one piece of news (i.e. in the `newsArticleList` there is a valid news piece in that position) but they are not properly displayed.
The implementation of populating the cell is:
```swift
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "reuseIdentifier", for: indexPath) as! NewsTableViewCell
        // Configure the cell...
        cell.TitleLabel.text = newsArticleList[indexPath.row].title
        cell.AuthorLabel.text = newsArticleList[indexPath.row].author
        if let releasedDate = newsArticleList[indexPath.row].publishedAt {
            // REF: https://stackoverflow.com/questions/43663622/is-a-date-in-same-week-month-year-of-another-date-in-swift
            if Calendar.current.isDate(releasedDate, equalTo: Date(), toGranularity: .month) {
                cell.RECENT.isHidden = false
            } else {
                cell.RECENT.isHidden = true
            }
        }
        return cell
    }
```
which I think have particular strategies, and the stack view setup for the cell is stacking the three labels, adding constraints of stack to margin, and making content distribution fill proportionally. Other cells look right but some of them won't populate correctly. Also, by scrolling, random cells that was scrolled out of screen then back could become blank as well, with console printing errors like: 
```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000019b1220 UITableViewCellContentView:0x7fa30e027050.bottomMargin == UIStackView:0x7fa30e000bd0.bottom   (active)>",
    "<NSLayoutConstraint:0x6000019b1270 UIStackView:0x7fa30e000bd0.top == UITableViewCellContentView:0x7fa30e027050.topMargin   (active)>",
    "<NSLayoutConstraint:0x6000019b1770 'UISV-canvas-connection' UIStackView:0x7fa30e000bd0.top == UILabel:0x7fa30e031930'Apple could be working on...'.top   (active)>",
    "<NSLayoutConstraint:0x6000019c68f0 'UISV-spacing' V:[UILabel:0x7fa30e031930'Apple could be working on...']-(0)-[UILabel:0x7fa30e032ba0'Romain Dillet']   (active)>",
    "<NSLayoutConstraint:0x6000019b1400 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x6000003f5960'UIViewLayoutMarginsGuide']-(8)-|   (active, names: '|':UITableViewCellContentView:0x7fa30e027050 )>",
    "<NSLayoutConstraint:0x6000019b23a0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa30e027050.height == 136   (active)>",
    "<NSLayoutConstraint:0x6000019b1360 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x6000003f5960'UIViewLayoutMarginsGuide']   (active, names: '|':UITableViewCellContentView:0x7fa30e027050 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000019c68f0 'UISV-spacing' V:[UILabel:0x7fa30e031930'Apple could be working on...']-(0)-[UILabel:0x7fa30e032ba0'Romain Dillet']   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```
which is a huge amount of texts... Is there any idea why this is happening? Thank you very much!

**Comment by JohnReddyZhang** [comment]
This error goes away by checking it's content view Size inspector's `Follow Readable Width`, but I am not sure why it works...

**Comment by susanstevens** [comment]
It's a little hard to tell without seeing your layout constraints, but I'm suspicious of the constraints between the stack view and one of your labels. I'd recommend placing all of your labels inside the stack view, if they aren't already. Then, the stack view will take care of laying out all of its subviews. Adding layout constraints between a stack view and its subviews isn't necessary (and may cause auto layout to break some constraints).

I'm not sure why `Follow Readable Width` solved this. That property has to do with the margins Apple thinks a cell should have for its contents to be "readable". Maybe using those margins adjusted something else in a way that resolved the issue?

**Comment by JohnReddyZhang** [comment]
Not sure neither. Now I uncheck that option the problem does not reproduce... Pretty sure the labels are in there right place and stack has constraints to the margins set. 

I suspect it might be something wrong with the spacing between those labels, since I set it to 0 before and changed it to standard.

However changing it back to 0 still won't reproduce the problem. I'll just let it go for now... 

Thank you very much for the answer!
