### ISSUE TITLE
Activity Indicator

### ISSUE THREAD

**Issue by Celiajm** [uchicago-mobi/MPCS51030-2019-Winter-Forum#83]
I've been having some issues with my UIActivityIndicator which should be animating when the WKWebView is loading. I've been having Unexpectedly found nil while unwrapping an optional value which is pointing to a .stopAnimating() method being run inside the WKWebView didFinish navigation method. I've double checked that my IBOutlet is hooked up to the code, but still have been unsuccessful in fixing this. Does anyone have any ideas what might be causing this?

**Comment by susanstevens** [comment]
It sounds like the `UIActivityIndicator` itself is nil when you call `stopAnimating()`. Do you have any code that's changing the activity indicator before `stopAnimating()` is called?

**Comment by Celiajm** [comment]
Nope, that's the weird thing, and why I originally thought that it was just that the IBOutlet wasn't correctly hooked up. The only place that `UIActivityIndicator` is being called is in the `didFinish navigation`method.

**Comment by liuwinshen** [comment]
I'm having the exact same issue, for both my ActivityIndicator and label (for the article source). I have also double checked the IBOutlets are hooked up properly and have no idea why it still crashes...

**Comment by liuwinshen** [comment]
@Celiajm It sounds like you created the indicator from the storyboard, but in case you created the `WebView` programmatically, try doing it from the storyboard.

I had created my `WebView` programmatically and gotten those errors with the `activity indicator`, but I just created it from the storyboard and it worked!

**Comment by susanstevens** [comment]
@celiajm any luck with this? If the issue is still happening, you might want to try setting a breakpoint in viewDidLoad and then stepping through your code to see where the activity indicator becomes nil.

**Comment by Celiajm** [comment]
So I fixed it the opposite way to @liuwinshen . I had created the webView from storyboard originally, but once I did it programmatically it worked fine!

**Comment by susanstevens** [comment]
Awesome! Sometimes it's easier to pick one approach to creating your layout for a particular screen -- either programmatically or with storyboard -- rather than mixing the two.

If you added a label in storyboard, for instance, and then created a web view programmatically and set it to be your root view (`view = webView`), this will cause your label to be removed from the view hierarchy and deallocated. But creating both the label and web view programmatically (or creating both in storyboard) resolves this issue.
