### ISSUE TITLE
Make UIActivityIndicatorView background (with gray color) larger?

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#85]
So I am trying to make a spinner that is a bit different from original implementation, i.e. have a background color and the background a bit larger than the spinner itself. 
I found a [tutorial](https://coderwall.com/p/su1t1a/ios-customized-activity-indicator-with-swift) that makes such spinner but the author achieved through adding another view, but I wonder if there is a way to achieve this by just adjusting the property itself? 
Thanks! 

![](https://coderwall-assets-0.s3.amazonaws.com/uploads/picture/file/3278/iOS_Simulator_Screen_Shot_Aug_14__2014__11.35.59_AM.png)

**Comment by susanstevens** [comment]
Good question! Even though spinners like this are really common, Apple doesn't provide any out-of-the-box way to achieve this look. I would guess that most apps with spinners like this are doing something similar to the tutorial you described.

**Comment by JohnReddyZhang** [comment]
Hmmm got it, guess I'll try to implement that later if I got time then lol. Thank you very much for that! I seen such spinners all the time and I thought it was something built in lol
