### ISSUE TITLE
Make performSegue use what is set in prepare(for segue)?

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#88]
I am trying to use `performSegue` function to achieve the requirements in extra credit. But it seems that `performSegue` is not behaving as I thought it should be.

I have a function `selectFirstItem` in `MasterViewController` that selects the first item in table and performs the show detail segue using `self.performSegue(withIdentifier: "showDetail", sender: initialIndexPath)` (I have the show detail segue identifier set to "showDetail")
I have the `prepare(for segue)` function that set's destination's article property.

A `searchAndRefresh` function that performs the search and set the article list property, and this function is called in `MasterViewController`'s `ViewDidLoad`. 
In the completion (which receives valid news value) block of `searchAndRefresh`, I set the news article property, and then call `selectFirstItem` function. 

Then in `DetailViewController` the webView load is called in its `ViewDidLoad`. 

This structure works fine with after the table loads selecting a piece of news but won't select the first piece of news on initial loading. 

What I expect is to let this performSegue do what is defined in `prepare(for segue)`, why is it not doing so? should I explicitly call `self.prepare()` to achieve that? Thank you very much!

**Comment by chelseatroy** [comment]
So, to clarify, is it working for every table cell except for the first one?

**Comment by JohnReddyZhang** [comment]
The issue was that selecting any cell using touch works, but "auto displaying the first cell's url in detail view" went wrong. However turns out I was trying to select the first item in the table by calling `selectFirstItem` before the table was populated using `tableView.reloadData()`. That's why it did not work.

**Comment by chelseatroy** [comment]
Fantastic. Glad you figured it out! Let me know if you have any further issues.
