### ISSUE TITLE
Keywords for Searching

### ISSUE THREAD

**Issue by tieyong** [uchicago-mobi/MPCS51030-2019-Winter-Forum#89]
I'm trying to pass the search keywords to my search service, but I noticed that my code only works for single keyword search. For multiple keywords separated by space, it won't work. Do I need to process the user input by replacing ' ' with '+'?

**Comment by hbennett766** [comment]
Either + or %20 or some other url blank space encoding character, I honestly don’t know which. But you are correct that your url will blow up if you try and give it whitespace.

**Comment by susanstevens** [comment]
Yep, the right thing to do here is to make sure your search term is properly encoded (i.e., spaces are replaced with %20). But for this assignment, you can assume that the user will only search for a single word at a time.

You would obviously not want to assume this in a real-world app. 😅
