### ISSUE TITLE
FoodTracker image in landscape orientation

### ISSUE THREAD

**Issue by skoop12** [uchicago-mobi/MPCS51030-2019-Winter-Forum#9]
I followed the food tracker guide for creating a UIImage (set aspect ratio constraint 1:1) and it looks right in portrait orientation, but the image doesn't resize correctly when the phone is rotated (and I can't scroll down on the simulator to view the rest of the photo).  Is this fine for now since we haven't finished the tutorial, or does anyone know how to fix the resizing issue?

Thanks!

<img width="334" alt="screen shot 2019-01-13 at 9 38 45 pm" src="https://user-images.githubusercontent.com/37815199/51095629-bebd3d00-177b-11e9-89a6-676bef11ab2b.png">

<img width="665" alt="screen shot 2019-01-13 at 9 39 00 pm" src="https://user-images.githubusercontent.com/37815199/51095633-c1b82d80-177b-11e9-929b-38ed75895308.png">

**Comment by susanstevens** [comment]
This is fine! In practice, you would probably use a `UIScrollView` to enable scrolling, which is something we'll talk about next class.

**Comment by skoop12** [comment]
Ok thanks!
