### ISSUE TITLE
About Extension

### ISSUE THREAD

**Issue by tieyong** [uchicago-mobi/MPCS51030-2019-Winter-Forum#93]
Is it possible for us to get an extension for Assignment 5 since we have proposal to work on? Also, I think I have many problems regarding search/webview stuff such that I want to attend tomorrow's OH.

**Comment by susanstevens** [comment]
No, I want everyone to have a full week for the next assignment, plus three weeks to work on final projects. So this assignment will still be due before class tomorrow.
