### ISSUE TITLE
preferredDisplayMode

### ISSUE THREAD

**Issue by boyangqu** [uchicago-mobi/MPCS51030-2019-Winter-Forum#94]
I have figured out everything else for the master and detail view, but I can't get them to display together on a single page. Added "splitViewController?.preferredDisplayMode = .allVisible" under the viewDidLoad() function in MasterViewController class, but nothing changed. It there anything wrong with my code?

**Comment by boyangqu** [comment]
It works with horizontal orientation and ipad though, is this a problem then?

**Comment by hbennett766** [comment]
This sounds correct. Portrait mode iPhones won’t display both at the same time, there isn’t enough horizontal real estate.
