### ISSUE TITLE
UIActivityIndicator not displaying.

### ISSUE THREAD

**Issue by lizefei** [uchicago-mobi/MPCS51030-2019-Winter-Forum#95]
I tried to create the activity indicator programmatically, but it never shows the indicator. But the web page shows fine.
I can see "start loading" printed in console, but no animation in screen.
Here is my code, can I have some help?

Sorry, I have deleted my code.

**Comment by hbennett766** [comment]
It looks like you’re overriding your view to be the webView, which is fine. However, you’re then adding the activity indicator as a subview to view, which doesn’t exist anymore. Use your webView as the base for setting the center and then adding the subviews.

**Comment by lizefei** [comment]
> It looks like you’re overriding your view to be the webView, which is fine. However, you’re then adding the activity indicator as a subview to view, which doesn’t exist anymore. Use your webView as the base for setting the center and then adding the subviews.

I have changed to configure my actInd based on webView and addsubview to both the view and the webView, but I still can't see the activity indicator.
(But if I remove view = webView, I can see it, but the web page will not be loaded.)

**Comment by susanstevens** [comment]
I would try changing the color of your activity indicator. Is it possible that it _is_ displaying, but since it's white on a white background you just can't see it?

Also, please don't post your entire view controller next time! 🙂

**Comment by hbennett766** [comment]
There's also a frame issue here. The webView frame is (0,0,0,0), which means setting the center of the activity indicator to the center of the webView (nothing) means that the activity indicator frame will also be nothing.

**Comment by hbennett766** [comment]
You could always go the route of implementing your webView as a subview of view. This would mean you delete the `loadView` method and do all your setup inside `viewDidLoad`. This architecture would mean view has webView as a subview, and webView has activityIndicator as a subview.

```
// webView setup
view.addSubview(webView)
// activity indicator setup
webView.addSubview(activityIndicatorView)
```

Whichever way you choose, check the frames of everything you instantiate, to make sure they have the values you expect.

**Comment by lizefei** [comment]
Thanks, but I solve it by adding web view by storyboard.
