### ISSUE TITLE
Activity Indicator Animation works, but don't see article show up after that 

### ISSUE THREAD

**Issue by eealexander2** [uchicago-mobi/MPCS51030-2019-Winter-Forum#98]
My activity indicator successfully starts/stops loading when the article has loaded, but now I don't see the article anymore. Any ideas?

**Comment by hbennett766** [comment]
This could by a myriad of things. Can you push your code to your repo? I'll check it out.

**Comment by eealexander2** [comment]
just pushed. thanks very much!

**Comment by hbennett766** [comment]
Two reasons why this is happening:

1. You're adding a `newsOutletView` on top of your web view. Just delete that whole thing. What you're calling `webKit` is actually the `webView` that will be loading the web page.

2. Your urls are all http, but you don't allow for unsecure urls at the moment. To allow for http as wel as https, add the app transport security settings key in your plist, then add the allows arbitrary loads key, and set its value to YES

https://mk0resourcesinfm536w.kinstacdn.com/wp-content/uploads/062616_1323_iOSApplicat2.png

A few other things I updated, including losing calls to `self` and safely dealing with turning a string into a URL:
```
if let url = URL(string: urlString) {
   webView.addSubview(activityIndicator)
   activityIndicator.startAnimating()
   
    let request = URLRequest(url: url)
     webView.load(request)
}
```

Lmk if this sample code makes sense within the context of what you currently have! I shuffled and renamed some things, but the basic architecture is the same.

**Comment by eealexander2** [comment]
Thanks so much! The reason why I added the  newsOutletView on top of the webView was bc I couldn't see it otherwise. i will figure out a different/better way to do this. Thanks again!

**Comment by hbennett766** [comment]
I tested it with this sample I wrote above, and everything is working. If those two steps don’t fix it, lmk

**Comment by eealexander2** [comment]
Those steps fix it, but now I don't see the bottom newsOutletView. I'll figure out how to make it appear besides making it a subview of the webkit

**Comment by hbennett766** [comment]
Ohhhhh that was the little view that was displaying the source? Sorry I thought you were trying to load the web view in there. You should be able to add it as a webView subview. Make sure its frame is set up properly? Correct x and y positions, as well as correct width and height.

**Comment by eealexander2** [comment]
yeah i'm not sure why adding it as a subview of the webView makes the article not show up, even when i've set the frame
